### PR TITLE
Next

### PR DESCRIPTION
**Pull request by emarsman**
I think this is ready to do a fab release to merge next into master. I plan on doing this tomorrow. 

One question on the message-format submodule. When I do a 'git submodule' in my shell, it shows

77718cfc70f76b687154756344e1a52b6f734ec9 src/libs/openxc-message-format (v0.4.0

But the 77718* commit should be versions 0.5.0. Where does the submodule get that version info?

### CODE REVIEW

**Comment by peplin** [comment]
LGTM - the version info display is from `git describe` and that'll come from making a new tag, e.g. https://github.com/openxc/openxc-message-format/releases

**Comment by emarsman** [comment]
@peplin tried the fab release command. Ran into an error with gpg signing. Looked around a little bit, but did you have instructions on how to set this up?

Error message while fab is trying git tag -as:

gpg: directory `/home/vagrant/.gnupg' created
gpg: new configuration file `/home/vagrant/.gnupg/gpg.conf' created
gpg: WARNING: options in `/home/vagrant/.gnupg/gpg.conf' are not yet active duri
ng this run
gpg: keyring `/home/vagrant/.gnupg/secring.gpg' created
gpg: keyring `/home/vagrant/.gnupg/pubring.gpg' created
gpg: skipped "Eric Marsman <emarsman@gmail.com>": secret key not available
gpg: signing failed: secret key not available
error: gpg failed to sign the data
error: unable to sign the tag
The tag message has been left in .git/TAG_EDITMSG

Fatal error: local() encountered an error (return code 128) while executing 'git
 tag -as v7.1.0'

Aborting.
vagrant@vagrant-ubuntu-precise-64:~/vi-firmware$

**Comment by peplin** [comment]
Looks like you figured it out, I see the signed tag - thanks!

**Comment by emarsman** [comment]
yeah. took forever to generate the gpg key in vagrant. Is vi-firmware the only repo where gpg is required to create a tag?

**Comment by peplin** [comment]
No, they all require signed tags to protect against the history being altered - here's a little info http://gitready.com/advanced/2014/11/02/gpg-sign-releases.html and a much longer backstory: http://mikegerwitz.com/papers/git-horror-story

**Comment by emarsman** [comment]
I'll read up. How is that enforced? I was able to release message-format without gpg.

**Comment by peplin** [comment]
It's just "enforced" by the automated release scripts, they use the `-s` flag with `git tag` - the message format might not have. I actually think that's an oversight - did you run `make` before tagging that release? The generated protobuf stubs may not be updated.

**Comment by emarsman** [comment]
I didn't, but make was run here: https://github.com/openxc/openxc-message-format/commit/3bb427338bc52b59921504727e77160b72242f3b

There is no release script/process for message-format right? I'll add that as an issue there. 

If it's just the release scripts, there's nothing to prevent somebody from manually tagging (like I did). Not sure if there's a way around that.

**Comment by peplin** [comment]
:+1: looks like they're up to date, but we should add an automated release script to make sure, shouldn't be hard to copy over one of the fabfiles. If you make an issue that'd be great.

**Pull request merged**
